config:
  target: 'http://localhost:3000'
  http:
    timeout: 10 # Responses have to be sent within 10 seconds or the request will be aborted

  phases:
    # Create 100 virtual users every second for 60 seconds
    - duration: 60 # seconds
      arrivalRate: 100 # virtual users

scenarios:
  - name: 'Load test get reviews request'
    flow:
      - get:
          url: '/reviews'
          expect:
            - statusCode: 200
      # - think: 3
  # - name: 'Load test get meta request'
  #   flow:
  #     - get:
  #         url: '/meta'
  #         expect:
  #           - statusCode: 200
